name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js x64
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'

      - name: Install build dependencies
        run: |
          npm ci
          npm run build-dist

      - name: Run unit tests
        run: |
          npm run test-unit-ci

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ${{ github.workspace }}/coverage/vitest/unit/coverage-final.json
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
          disable_search: true

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js x64
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'

      - name: Install build dependencies
        run: |
          npm ci
          npm run build-dist

      - name: Run integration tests
        run: |
          npm run test-integration-ci

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ${{ github.workspace }}/coverage/vitest/integration/coverage-final.json
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
          disable_search: true

  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js x64
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'

      - name: Install build dependencies
        run: |
          npm ci
   
      - name: Build docs
        run: |
          npm run docs
